endpoints:
  sensitive: false
  hypermedia:
    enabled: true

logging:
  level:
    root: WARN

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  main:
    banner-mode: "off"
